name: Run

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 10 * 1-4,9-12 6'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install; npm run start

